name: Fabián Uribe
url: http://fabianuribe.com
css_path: /assets/css/
images_path: /assets/images/
description: "A thing or two about software development and computer science."
markdown: kramdown
highlighter: rouge
permalink: none
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data
gems:
  - jekyll-gist
exclude: [Gemfile, Gemfile.lock, node_modules, package.json, npm-debug.log, Gruntfile.js, css]
