name: Fabián Uribe
markdown: redcarpet
highlighter: pygments
permalink: none
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data
gems:
  - jekyll-gist
